---

- set_fact:
    privatekey: 'srv_sec_{{ NAME_WIREGUARD }}'
    path_privatekey: '{{ PATH_WIREGUARD }}/srv_sec_{{ NAME_WIREGUARD }}.key'
    publickey: 'srv_pub_{{ NAME_WIREGUARD }}'
    path_publickey: '{{ PATH_WIREGUARD }}/srv_pub_{{ NAME_WIREGUARD }}.key'
  when: TYPE_WIREGUARD == 'server'

- set_fact:
    privatekey: 'cli_sec_{{ NAME_WIREGUARD }}'
    path_privatekey: '{{ PATH_WIREGUARD }}/cli_sec_{{ NAME_WIREGUARD }}.key'
    publickey: 'cli_pub_{{ NAME_WIREGUARD }}'
    path_publickey: '{{ PATH_WIREGUARD }}/cli_pub_{{ NAME_WIREGUARD }}.key'
  when: TYPE_WIREGUARD == 'client'

- name: Installation de Wireguard
  openbsd_pkg:
    name: wireguard-tools
    state: present

- name: Activer le transfert de paquets IPv4
  sysctl:
    name: net.inet.ip.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Création du dossier de configuration
  file:
    path: "{{ PATH_WIREGUARD }}"
    state: directory
    mode: '0700'

- name: Verification d'une cle privee existante
  stat:
    path: "{{ path_privatekey }}"
  register: stat_privatekey

- name: Creation de la cle privee 
  shell:
    cmd: wg genkey > {{ privatekey }}.key
    chdir: "{{ PATH_WIREGUARD }}"
  when: not stat_privatekey.stat.exists

- name: Modification des permissions sur la cle privee
  file:
    path: "{{ path_privatekey }}"
    state: file
    mode: '0600'

- name: Verification d'une cle public existante
  stat:
    path: "{{ path_publickey }}"
  register: stat_publickey

- name: Creation de la cle public
  shell:
    cmd: wg pubkey < {{ privatekey }}.key > {{ publickey }}.key
    chdir: "{{ PATH_WIREGUARD }}"
  when: not stat_publickey.stat.exists

- name: Recuperation de la cle privee
  shell: cat "{{ path_privatekey }}"
  register: VALUE_WIREGUARD
  changed_when: false

- name: Creation du fichier de configuration
  template:
    src: openbsd_server.j2
    dest: "{{ PATH_WIREGUARD }}/{{ INTERFACE_WIREGUARD }}.conf"
    owner: root
    group: wheel
    mode: 0600
  when: TYPE_WIREGUARD == 'server'

- name: Creation du fichier de configuration
  template:
    src: openbsd_client.j2
    dest: "{{ PATH_WIREGUARD }}/{{ INTERFACE_WIREGUARD }}.conf"
    owner: root
    group: wheel
    mode: 0600
  when: TYPE_WIREGUARD == 'client'

- name: Création de l'interface "{{ INTERFACE_WIREGUARD }}"
  template:
    src: openbsd_interface.j2
    dest: "/etc/hostname.{{ INTERFACE_WIREGUARD }}"
    owner: root
    group: wheel
    mode: 0640
