# galaxy.yml

namespace: ansible
name: sysadmin
description: Collection for Sysadmin
version: 1.0.0
authors:
  - Zami3l

readme: README.md
repository: https://github.com/Zami3l/ansible.sysadmin.git
homepage: https://github.com/Zami3l/ansible.sysadmin.git
issues: https://github.com/Zami3l/ansible.sysadmin/issues
documentation: https://github.com/Zami3l/ansible.sysadmin/blob/main/README.md

license_file: LICENSE
license: []

tags:
  - linux
  - bsd
  - system

dependencies: {}

build_ignore: []
