---

- name: Create user _pfbadhost
  user:
    name: _pfbadhost
    shell: /sbin/nologin
    home: /var/empty
    state: present

- name: Add binary pf-badhost.sh
  get_url:
    url: https://geoghegan.ca/pub/pf-badhost/latest/pf-badhost.sh
    dest: /usr/local/bin/pf-badhost
    mode: 0755
    owner: root
    group: wheel

- name: Create log directory
  file:
    path: /var/log/pf-badhost
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Create required files
  file:
    path: "{{ item }}"
    state: touch
    mode: 0640
    owner: _pfbadhost
    group: wheel
  loop:
      - /etc/pf-badhost.txt
      - /var/log/pf-badhost/pf-badhost.log
      - /var/log/pf-badhost/pf-badhost.log.0.gz

- name: Install doas oksh mawk
  pkgng:
    name: doas, oksh, mawk
    state: present

- name: Create symbolic link
  file:
    src: /usr/local/bin/oksh
    dest: /usr/local/bin/ksh
    owner: root
    group: wheel
    state: link

- name: Create configuration doas
  copy:
    src: /usr/local/etc/doas.conf.sample
    dest: /usr/local/etc/doas.conf
    owner: root
    group: wheel
    remote_src: yes
    force: no

- name: Check if permit Pf-Badhost exists
  shell: cat /usr/local/etc/doas.conf
  register: check_permit

- name: Add rules for configuration doas
  blockinfile:
    path: /usr/local/etc/doas.conf
    marker: "# {mark} Pf-Badhost"
    block: |
      permit root
      permit nopass _pfbadhost cmd /sbin/pfctl args -nf /etc/pf.conf
      permit nopass _pfbadhost cmd /sbin/pfctl args -t pfbadhost -T replace -f /etc/pf-badhost.txt
      # Optional rule for authlog scanning
      permit nopass _pfbadhost cmd /usr/bin/bzcat args -f /var/log/auth.log /var/log/auth.log.0.bz2
  when: check_permit.stdout.find('Pf-Badhost') == -1

- name: Create sub-rules pf directory
  file:
    path: /etc/pfsub
    state: directory
    mode: 0640
    owner: root
    group: wheel

- name: Add sub-rules pfBadHost
  copy: 
    dest: /etc/pfsub/pfbadhost.conf
    content: |
        set limit table-entries 400000
        table <pfbadhost> persist file "/etc/pf-badhost.txt"
        block in quick on $iface_wan from <pfbadhost>
        block out quick on $iface_wan to <pfbadhost>

- name: Include pfBadHost on pf.conf
  lineinfile:
    path: /etc/pf.conf
    regexp: '^include "/etc/pfsub/pfbadhost.conf"'
    insertafter: '[i|I]nclude tables'
    line: include "/etc/pfsub/pfbadhost.conf"
  notify:
      - reload_pf_rules

- name: reload_pf_rules
  shell:
    cmd: pfctl -f /etc/pf.conf
  register: output_reload_rules
  ignore_errors: yes
  notify:
      - upgrade_ip_list

- name: load_pf_module
  shell: kldload -n pf
  when: '"No such file or directory" in output_reload_rules.stderr'
  notify:
      - reload_pf_rules

- name: Add crontab for upgrade ip address list
  cron:
    name: Upgrade ip address list pf-badhost
    minute: "0"
    hour: "0"
    job: "SHELL=/bin/sh pf-badhost -O freebsd"
    user: _pfbadhost

