---

- name: Installation des pre-requis
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Ajout GPG key docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Ajout repository docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Installation de docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: present

- name: Installation de docker-compose
  apt:
    name:
      - docker-compose
    state: present
