---

- name: Creation des groupes
  group:
    name: "{{ item.name }}"
    state: present
  loop: "{{ GROUPS }}"

- name: Creations des utilisateurs
  user:
    name: "{{ item.name }}"
    groups: "{{ item.group }}"
    state: present
  loop: "{{ USERS }}"

- name: Creation du repertoire /etc/ssh/authorized_keys/
  file:
    path: /etc/ssh/authorized_keys
    state: directory
    mode: 0755

- name: Ajout des cles ssh des utilisateurs dans /etc/ssh/authorized_keys/
  copy:
    src: "{{ item.path_ssh_keys }}"
    dest: "/etc/ssh/authorized_keys/{{ item.name }}"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0600
  loop: "{{ PUBKEY }}"

- name: Configuration ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^(#* *%*)?{{ item.name }}"
    line: "{{ item.name }} {{ item.value }}"
  loop:
    - { name: Port, value: "{{ PORT_SSH }}" }
    - { name: PermitRootLogin, value: "no" }
    - { name: PubkeyAuthentication, value: "yes" }
    - { name: AuthorizedKeysFile, value: "/etc/ssh/authorized_keys/%u" }
    - { name: PasswordAuthentication, value: "yes" }
    - { name: KerberosAuthentication, value: "no" }
    - { name: GSSAPIAuthentication, value: "no" }
  notify:
    - restart_sshd

- name: Autorisation groupe wheel a utiliser sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    create: yes
    regexp: '^(#* *%*)?wheel'
    line: '%wheel ALL=(ALL) ALL'
  when: ansible_distribution != 'OpenBSD'

- name: Autorisation groupe wheel a utiliser doas
  lineinfile:
    dest: /etc/doas.conf
    state: present
    create: yes
    regexp: '^(#* *%*)?permit: wheel'
    line: 'permit :wheel'
  when: ansible_distribution == 'OpenBSD'
