---

#####################
#     ArchLinux     #
#####################

- block:

  - name: Upgrade all packages on ArchLinux
    pacman:
      update_cache: yes
      upgrade: yes

  when: ansible_facts['os_family'] == 'Archlinux'

#####################
#       Debian      #
#####################

- block:

  - name: Upgrade all packages on Debian
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      autoclean: yes

  - name: Check update packages
    shell: grep -E "^$(date +%Y-%m-%d) .+ upgrade" /var/log/dpkg.log | cut -d " " -f 3-
    register: packages_update

  - name: Show packages
    debug:
      msg: "{{ packages_update.stdout_lines }}"

  when: ansible_facts['os_family'] == 'Debian'

#####################
#      OpenBSD      #
#####################

- block:

  - name: Update all packages on OpenBSD
    openbsd_pkg:
      name: '*'
      state: latest

  when: ansible_facts['os_family'] == 'OpenBSD'

#####################
#       RedHat      #
#####################

- block:

  - name: Upgrade all packages on Family RedHat 8 or Fedora
    dnf:
      name: '*'
      state: latest

  when: (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8') or ansible_facts['distribution'] == 'Fedora'

- block:

  - name: Upgrade all packages on Family RedHat 7
    yum:
      name: '*'
      state: latest

  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
