---

- name: Installation des packages
  openbsd_pkg:
    name: wireguard-tools
    state: latest

- name: Activation du transfert de paquets IPv4 et IPv6
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.inet.ip.forwarding
    - net.inet6.ip6.forwarding

- name: Creation du dossier de configuration
  file:
    path: "{{ PATH_DIR_WIREGUARD }}"
    state: directory
    mode: '0700'

- name: Copie du fichier Mullvad
  copy:
    src: "{{ SRC_FILE_MULLVAD }}"
    dest: "{{ PATH_FILE_WIREGUARD }}"
    owner: root
    group: wheel
    mode: 0600

- name: Recuperation adresse ip interface
  shell:
    cmd: grep Address "{{ PATH_FILE_WIREGUARD }}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'
  register: IP_INTERFACE_WIREGUARD

- name: Creation configuration wireguard
  lineinfile:
    dest: "{{ PATH_FILE_WIREGUARD }}"
    state: absent
    regexp: "^(#* *%*)?{{ item }}"
  loop:
    - Address
    - DNS

- name: Creation interface {{ INTERFACE_WIREGUARD }}
  blockinfile:
    path: /etc/hostname.{{ INTERFACE_WIREGUARD }}
    create: yes
    marker: "# {mark} ANSIBLE - Interface {{ INTERFACE_WIREGUARD }}"
    block: |
      inet {{ IP_INTERFACE_WIREGUARD.stdout }} 255.255.255.255
      up

      !/usr/local/bin/wg setconf {{ INTERFACE_WIREGUARD }} {{ PATH_DIR_WIREGUARD }}/{{ INTERFACE_WIREGUARD }}.conf
