---

- name: Create user _pfbadhost
  user:
    name: _pfbadhost
    shell: /sbin/nologin
    home: /var/empty
    create_home: no
    state: present

- name: Add binary pf-badhost.sh
  get_url:
    url: https://geoghegan.ca/pub/pf-badhost/latest/pf-badhost.sh
    dest: /usr/local/bin/pf-badhost
    mode: 0755
    owner: root
    group: bin

- name: Create log directory
  file:
    path: /var/log/pf-badhost
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Create required files
  copy:
    content: ""
    dest: "{{ item }}"
    mode: 0640
    owner: _pfbadhost
    group: wheel
    force: no
  loop:
      - /etc/pf-badhost.txt
      - /var/log/pf-badhost/pf-badhost.log
      - /var/log/pf-badhost/pf-badhost.log.0.gz

- name: Install ripgrep mawk
  openbsd_pkg:
    name: ripgrep, mawk
    state: present

- name: Create configuration doas
  file:
    path: /etc/doas.conf
    owner: root
    group: wheel
    state: touch

- name: Add rules for configuration doas
  blockinfile:
    path: /etc/doas.conf
    marker: "# {mark} Pf-Badhost"
    block: |
      permit nopass root as _pfbadhost
      permit nopass _pfbadhost cmd /sbin/pfctl args -nf /etc/pf.conf
      permit nopass _pfbadhost cmd /sbin/pfctl args -t pfbadhost -T replace -f /etc/pf-badhost.txt
      # Optional rule for authlog scanning
      permit nopass _pfbadhost cmd /usr/bin/zcat args -f /var/log/authlog /var/log/authlog.0.gz

- name: Create sub-rules pf directory
  file:
    path: /etc/pfsub
    state: directory
    mode: 0640
    owner: root
    group: wheel

- name: Add sub-rules pfBadHost
  copy: 
    dest: /etc/pfsub/pfbadhost.conf
    content: |
        table <pfbadhost> persist file "/etc/pf-badhost.txt"
        block in quick on $wan_if from <pfbadhost>
        block out quick on $wan_if to <pfbadhost>

- name: Include pfBadHost on pf.conf
  lineinfile:
    path: /etc/pf.conf
    regexp: '^include "/etc/pfsub/pfbadhost.conf"'
    insertafter: '[i|I]nclude tables'
    line: include "/etc/pfsub/pfbadhost.conf"
  notify:
      - reload_pf_rules

- name: reload_pf_rules
  shell:
    cmd: pfctl -f /etc/pf.conf
  register: output_reload_rules
  ignore_errors: yes
  notify:
      - upgrade_ip_list

- name: Add crontab for upgrade ip address list
  cron:
    name: Upgrade ip address list pf-badhost
    minute: "0"
    hour: "1"
    job: "SHELL=/bin/sh pf-badhost -O openbsd"
    user: _pfbadhost

